export enum Category {
    RENT = 'שכר דירה',
    BUILDING_MAINTENANCE = 'ועד בית',
    BILLS = 'חשבונות',
    INVESTMENT = 'השקעות',
    MORTGAGE = 'משכנתא',
    MORTGAGE_LIFE_INSURANCE = 'ביטוח חיים למשכנתא',
    MORTGAGE_APARTMENT_INSURANCE = 'ביטוח דירה למשכנתא',
    DIGITAL_SERVICES = 'שירותים דיגיטליים',
    HEALTH_INSURANCE = 'קופות חולים',
    KINDERGARTEN = 'גנים',
    EXTRACURRICULARS = 'חוגים',
    BUDDY = 'באדי',
    CAR_INSURANCE = 'ביטוחי רכב',
    LIFE_INSURANCE = 'ביטוח חיים פרטי',
    FUEL = 'דלק',
    RESTAURANTS = 'מסעדות',
    GROCERIES = 'סופרמרקט',
}
