export enum Category {
    RENT = 'RENT',
    KINDERGARTEN = 'KINDERGARTEN',
    FUEL = 'FUEL',
    BILLS = 'BILLS',
    CAR_INSURANCE = 'CAR INSURANCE',
    LIFE_INSURANCE = 'LIFE INSURANCE',
    RESTAURANTS = 'RESTAURANTS',
    GROCERIES = 'GROCERIES',
    DIGITAL_SERVICES = 'DIGITAL SERVICES'
}
